name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  scala:
    uses: nok-ie/github-workflows/.github/workflows/scala-deploy-gcp.yml@main
    with:
      SBT_PROJECT_ID: root
      GCP_CLOUD_RUN_SERVICE: api
    secrets:
      GH_TOKEN_READ_PACKAGES: ${{ secrets.GH_TOKEN_READ_PACKAGES }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
